spring.application.name=game-service
server.port=8084
logging.level.org.springframework.web=DEBUG
spring.main.web-application-type=reactive
server.netty.connection-timeout= 5000ms

spring.profiles.active=local

logging.level.root=OFF